/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    Icon: typeof import('./components/Icon/index.vue')['default']
    MenuItem: typeof import('./components/SideMenu/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./components/SideMenu/index.vue')['default']
  }
}
